# Server
server.port=8082

# Application name
spring.application.name=room-service

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/connecthub_room?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Bhumi#1705
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Auth Service URL (room service calls auth service to verify userId)
auth.service.url=http://localhost:8081

# Logging
logging.level.com.connecthub=DEBUG
