# Server
server.port=8087

# Application name
spring.application.name=websocket-service

# JWT Secret — same as auth-service
jwt.secret=ConnectHubSuperSecretKeyForJWTTokenGeneration2024MustBe256BitsLong

# Other service URLs
message.service.url=http://localhost:8083
presence.service.url=http://localhost:8084
notification.service.url=http://localhost:8085
room.service.url=http://localhost:8082

# Logging
logging.level.com.connecthub=DEBUG
logging.level.org.springframework.web.socket=DEBUG

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true