# Server — Render injects PORT env var; fallback to 8761 for local
server.port=${PORT:8761}

# Application name
spring.application.name=eureka-server

# Eureka config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka dashboard
eureka.server.enable-self-preservation=false

# Logging
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
